name: 08 - using variables
on:
    push:
    workflow_dispatch:
env:
    workflow-var: "i am a workflow env"
    overwritten: "i will be overwritten in job"
jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "i am a job env"
            overwritten: "i am the job env that overwrites the workflow env"
        steps:
            - name: print Env variables
              env:
                STEP_VAR: "i am a step env"
                step-var2: "i am another step env"
              run: |
                 echo "step env var: ${{env.STEP_VAR}}"
                 echo "step env var2: ${{env.step-var2}}"
                 echo "job env var: ${{env.JOB_VAR}}" 
                 echo "workflow env var: ${{env.workflow-var}}"
                 echo "overwritten var: ${{env.overwritten}}"
                 echo "overwritten job level : ${{env.overwritten}}"
            - name: overwride job variables
              env:
                OVERWRITTEN: "I have been overwritten at the step level"
              run: |
                echo "overwritten var at step level: ${{env.OVERWRITTEN}}"